apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cccr-dynamic-pvc
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Mi
  #storageClassName: "standard" //minikube default 는 이것이다.
  storageClassName: "glusterfile"
