apiVersion: v1
kind: Pod
metadata:
  name: limits-pod
spec:
  containers:
  - image: c1t1d0s7/cccr
    name: limits-pod
    resources:
    #request 는 선언하지 않았으나, limit와 동일한 값으로 설정된다!
      limits:
        cpu: 0.5
        memory: 20Mi
