apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cccr
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cccr
  template:
    metadata:
      labels:
        app: cccr
    spec:
      containers:
      - name: cccr
        image: c1t1d0s7/cccr
#여기 부분이 readinessProbe
        readinessProbe:
        # exec: [ 'ls', '/var/ready' ] 아래와 동일
          exec:
            command:
              - ls
              - /var/ready
        ports:
        - containerPort: 8080
