apiVersion: batch/v1
kind: Job
metadata:
  name: cccr
spec:
  template:
    metadata:
      labels:
        app: cccr
    spec:
      #재시작 정책: always(default) / never(재시작하지않음) / OnFailure(실패났을 때만 재시작)
      restartPolicy: OnFailure
      containers:
      - name: cccr
      #sleep을 사용하기 위해 busybox를 사용했다.
        image: busybox
        command: ["sleep", "10"]
