apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: cccr
spec:
  selector:
    matchLabels:
      app: cccr
  template:
    metadata:
      labels:
        app: cccr
    spec:
#daemonset에만 있는 것은 아니다.
#pod.spec 등에도 존재한다.
      nodeSelector:
        node: development
      containers:
      - name: cccr
        image: c1t1d0s7/cccr
        ports:
        - containerPort: 8080
