#error: unable to recognize "./cccr-replicaset.yml": no matches for kind "ReplicaSet" in version "apps/v1beta2"
#apps/v1beta2 -> apps/v1
apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: cccr
spec:
  replicas: 3
  selector:
#레플리케이션 컨트롤러의 selector에 해당  
    matchLabels:
      app: cccr
#여기에 추가하면 아래 labels 에 복수로 선언되어 있어야 되지 그렇지 않으면, 생성 시 오류가 발생한다!
##The ReplicaSet "cccr" is invalid: spec.template.metadata.labels: Invalid value: map[string]string{"app":"cccr"}: `selector` does not match template `labels`
#      dev: qa
  template:
    metadata:
      labels:
        app: cccr
#아래와 같이 위 matchLabels 과 상관없이 추가되어도 무방하다.        
#        dev: qa
    spec:
      containers:
      - name: cccr
        image: c1t1d0s7/cccr
        ports:
        - containerPort: 8080
