#base image
FROM node:slim
#컨테이너 내부의 작업 디렉토리
WORKDIR /usr/src/app
#add와 동일, host의 현재 디렉토리를 컨테이너 내부의 현재디렉토리로 복사하는 cmd
##이 예제에서는 COPY index.js /usr/src/app 과 동일함
COPY . . 
#이미지를 빌드할 때 실행할 cmd
RUN npm install ip
#ENTRYPOINT, CMD는 이미지가 컨테이너를 실행할 때 사용하는 cmd
##ENTRYPOINT, CMD 둘다 있으면, node index.js "Hello World!"
##둘다 있으면, ENTRYPOINT가 앞에 온다.
ENTRYPOINT ["node", "index.js"]
#실행할 Application
CMD ["Hello World!"]
#docker daemon에 알려줄 port 로 infomation 이다.
##다시 말해 없어도 동작하며, 강제성이 있는 것은 아니다.
EXPOSE 8080/tcp
